Update spring + spring boot
CAFDataProcessing/staging-service pull request #113
Opened 2022-05-10 09:17 UTC by rorytorneymf

2022-05-13 15:43 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](http://sou-jenkins2.swinfra.net:8080/job/Create-New-Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=CAFDataProcessing&REPO_NAME=staging-service&BRANCH_NAME=366015) to go ahead and create the build...

2022-05-13 15:46 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
http://sou-jenkins2.swinfra.net:8080/job/CAFDataProcessing/job/CAFDataProcessing~staging-service~366015~CI

2022-05-13 15:52 UTC, rorytorneymf commented on staging-service/src/main/java/com/github/cafdataprocessing/services/staging/StagingApi.java
> +    ResponseEntity<Void> createOrReplaceBatch(@ApiParam(value = "Identifies the tenant making the request." ,required=true) @RequestHeader(value="X-TENANT-ID", required=true) String X_TENANT_ID,@Size
Copied and modified in order to change `@Valid @RequestBody Object body` to `MultipartHttpServletRequest request`

2022-05-13 16:15 UTC, rorytorneymf commented on staging-service/src/main/java/com/github/cafdataprocessing/services/staging/dao/filesystem/FileSystemDao.java
> +                if (part.getSubmittedFileName() != null) {
I think `part.getSubmittedFileName() != null` is equivalent to `!fileItemStream.isFormField()`

2022-05-13 16:53 UTC, rorytorneymf commented on staging-service/src/main/java/com/github/cafdataprocessing/services/staging/StagingApi.java
> +    ResponseEntity<Void> createOrReplaceBatch(@ApiParam(value = "Identifies the tenant making the request." ,required=true) @RequestHeader(value="X-TENANT-ID", required=true) String X_TENANT_ID,@Size
Actually, I remember there's a way to do this in maven using the `gmavenplus-plugin`, I'll have a look at this on Monday

2022-05-14 04:16 UTC, dermot-hardy requested changes
I tried testing this and I'm finding that it abruptly disconnects if I send it large files.  I see the following in the log:

    Request processing failed; nested exception is org.springframework.web.multipart.MaxUploadSizeExceededException: Maximum upload size exceeded; nested exception is java.lang.IllegalStateException: org.apache.tomcat.util.http.fileupload.impl.FileSizeLimitExceededException: The field batch.json exceeds its maximum permitted size of 1048576 bytes.

I'm concerned that this is more than just a maximum size setting that needs to be adjusted.  The Staging Service is meant to stream the data through to disk, so that it never has to hold the entire request in memory at any one time.  This feels like it is trying to parse the entire request before it even calls into our code.

2022-05-16 16:12 UTC, rorytorneymf commented
> I tried testing this and I'm finding that it abruptly disconnects if I send it large files. I see the following in the log:
> 
> ```
> Request processing failed; nested exception is org.springframework.web.multipart.MaxUploadSizeExceededException: Maximum upload size exceeded; nested exception is java.lang.IllegalStateException: org.apache.tomcat.util.http.fileupload.impl.FileSizeLimitExceededException: The field batch.json exceeds its maximum permitted size of 1048576 bytes.
> ```
> 
> I'm concerned that this is more than just a maximum size setting that needs to be adjusted. The Staging Service is meant to stream the data through to disk, so that it never has to hold the entire request in memory at any one time. This feels like it is trying to parse the entire request before it even calls into our code.

Thanks. I've gone back to using `commons-fileupload` in this new PR:

https://github.com/CAFDataProcessing/staging-service/pull/115

Closing this PR.

2022-05-16 16:12 UTC, closed without merging