US607098: Change Instant.now to SimpleDateFormat
CAFDataProcessing/staging-service pull request #133
Opened 2022-11-17 07:23 UTC by raghavendran-gopalakrishnan

https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=607098

2022-11-17 10:06 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
http://sou-jenkins2.swinfra.net:8080/job/CAFDataProcessing/job/CAFDataProcessing~staging-service~US607098~CI

2022-11-17 17:45 UTC, dermot-hardy requested changes

2022-11-17 17:45 UTC, dermot-hardy commented on staging-service-shared/src/main/java/com/github/cafdataprocessing/services/staging/dao/filesystem/BatchNameProvider.java
> +import java.util.TimeZone;
We shouldn't be using any of these legacy date types.  You should be using the modern Date Time API (i.e. in the `java.time.` package.

- https://docs.oracle.com/javase/tutorial/datetime/iso/legacy.html

2022-11-21 13:36 UTC, dermot-hardy requested changes

2022-11-21 13:36 UTC, dermot-hardy commented on staging-service-shared/src/main/java/com/github/cafdataprocessing/services/staging/dao/filesystem/BatchNameProvider.java
> +        final DateTimeFormatter formatToday = DateTimeFormatter.ofPattern(DATE_TIME_ISO_PATTERN).withZone(ZoneOffset.UTC);
This will construct the formatter before each use.  It should only need to be constructed once.

2022-11-21 13:36 UTC, dermot-hardy commented on staging-service-shared/src/main/java/com/github/cafdataprocessing/services/staging/dao/filesystem/BatchNameProvider.java
> +        return cleanseTime(currentTimeAsString);
Still using `cleanseTime()` doesn't make much sense in the light of the other changes being made.

2022-11-21 15:37 UTC, dermot-hardy requested changes

2022-11-21 15:37 UTC, dermot-hardy commented on staging-service-shared/src/main/java/com/github/cafdataprocessing/services/staging/dao/filesystem/BatchNameProvider.java
> +        return formatToday.format(Instant.now()).replace(":", "");
But why would we need a `.replace(":", "")` when we're controlling the input format in the first place?  (That was my point before.)

2022-11-21 18:14 UTC, dermot-hardy requested changes

2022-11-21 18:14 UTC, dermot-hardy commented on staging-service-shared/src/main/java/com/github/cafdataprocessing/services/staging/dao/filesystem/BatchNameProvider.java
> +        return formatToday.format(Instant.now()).replace(":", "");
Call to `replace()` is still present even after the format string has been adjusted.

2022-11-21 18:19 UTC, dermot-hardy approved these changes

2022-11-22 08:58 UTC, frankmccarry approved these changes

2022-11-22 09:24 UTC, merged