SCMOD-11993: Update for release 1.2.0
CAFDataProcessing/staging-service pull request #69
Opened 2021-01-11 10:49 UTC by xbreizh

https://portal.digitalsafe.net/browse/SCMOD-11993

2021-01-11 10:52 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](http://sou-jenkins2.swinfra.net:8080/job/Create-New-Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=CAFDataProcessing&REPO_NAME=staging-service&BRANCH_NAME=SCMOD-11993) to go ahead and create the build...

2021-01-11 10:54 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
http://sou-jenkins2.swinfra.net:8080/job/CAFDataProcessing/job/CAFDataProcessing~staging-service~SCMOD-11993~CI

2021-01-12 14:48 UTC, dermot-hardy requested changes
If there are no new features then this should be 1.1.1

2021-01-12 17:54 UTC, rahul-kulkarni73 commented
Done.

2021-01-12 18:01 UTC, dermot-hardy approved these changes

2021-01-12 19:30 UTC, merged